spring:
  data:
    mongodb:
      uri: ${MONGO_URL}
      database: airecommendationfitness
  kafka:
    bootstrap-server: localhost:9092
    consumer:
      group-id: activity-processor-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.fitness.aiservice.model.Activity
        spring.json.trusted.packages: "*"
server:
  port: 5568

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:5565/eureka/
  instance:
    prefer-ip-address: false
    hostname: localhost

kafka:
  topic:
    name: activity-events

gemini:
  api:
    url: ${GEMINI_URL}
    key: ${GEMINI_KEY}